version: '3.8'

services:
  dummy-otel:
    image: ghcr.io/marinnedea/dummy-otel:v1.2.2
    ports:
      - "8000:8000"
    environment:
      OTEL_EXPORTER_OTLP_ENDPOINT: "http://host.docker.internal:4317"
    restart: unless-stopped
