apiVersion: apps/v1
kind: Deployment
metadata:
  name: dummy-otel
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: dummy-otel
  template:
    metadata:
      labels:
        app: dummy-otel
    spec:
      containers:
        - name: dummy-otel
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          ports:
            - containerPort: 8000
          env:
            - name: OTEL_EXPORTER_OTLP_ENDPOINT
              value: "{{ .Values.env.OTEL_EXPORTER_OTLP_ENDPOINT }}"
