apiVersion: v1
kind: Service
metadata:
  name: dummy-otel
spec:
  type: {{ .Values.service.type }}
  selector:
    app: dummy-otel
  ports:
    - port: {{ .Values.service.port }}
      targetPort: 8000
