replicaCount: 1

image:
  repository: ghcr.io/marinnedea/dummy-otel
  pullPolicy: IfNotPresent
  tag: "v1.2.1"

service:
  type: ClusterIP
  port: 8000

env:
  OTEL_EXPORTER_OTLP_ENDPOINT: "http://alloy:4317"
